export const USER_STATE_CHANGE = "USER_STATE_CHANGE";
export const USER_POST_CHANGE = "USER_POST_CHANGE";
export const USER_FOLLOWING_CHANGE = "USER_FOLLOWING_CHANGE";

export const USERS_DATA_CHANGE = "USERS_DATA_CHANGE";
export const USERS_POST_CHANGE = "USERS_POST_CHANGE";
